version: "3"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    depends_on:
      - cloudflared
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - ${HTTPPORT}:80/tcp
      - ${HTTPSPORT}:443/tcp
    environment:
      - PIHOLE_DNS_=cloudflared#5053
      - WEBPASSWORD=${WEBPASSWORD}
      - DNSSEC=true
    volumes:
      - ${CONFIG}:/etc/pihole
      - ${DNSMASQ}:/etc/dnsmasq.d
      - /etc/localtime:/etc/localtime:ro
    dns:
      - 127.0.0.1
    restart: unless-stopped

  cloudflared:
    image: visibilityspots/cloudflared
    container_name: cloudflared
    ports:
      - "5053:5053/tcp"
      - "5053:5053/udp"
    environment:
        PORT: 5053
        ADDRESS: 0.0.0.0
    volumes:
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped

networks:
  default:
    name: ${NETWORKNAME}
